#!/bin/sh

current_song="$(( $(cat $HOME/mus/current_song) - 1 ))"

if [ $current_song -gt "$(wc -l < $HOME/mus/playlist)" ]; 
	then current_song=1; 
else 
	if [ $current_song -lt 1 ]; 
		then current_song="$(wc -l < $HOME/mus/playlist)"; 
	fi
fi

change_cur_song $current_song
