#!/bin/sh

current_song="$(cat /tmp/mpv_mus/current_song)"

if [ "$1" = "-f" ]; then
	cat >> /tmp/mpv_mus/pl_temp
else
	sed "s/^/\/home\/$USER\/Musicas\//" >> /tmp/mpv_mus/pl_temp
fi

sed -n "1,${current_song} p" < /tmp/mpv_mus/playlist > /tmp/mpv_mus/pl_1
sed -n "$((current_song + 1)),$ p" < /tmp/mpv_mus/playlist > /tmp/mpv_mus/pl_2

cat /tmp/mpv_mus/pl_1 /tmp/mpv_mus/pl_temp /tmp/mpv_mus/pl_2 > /tmp/mpv_mus/playlist
rm /tmp/mpv_mus/pl_1 /tmp/mpv_mus/pl_temp /tmp/mpv_mus/pl_2 
