#!/bin/sh

chosen=$(cut -d ';' -f1 ~/.local/share/unicode | $MENU -i -l 30 | sed "s/ .*//" | sed "s/ .*$//g")

[ -z "$chosen" ] && exit

if [ -n "$1" ]; then
	xdotool type "$chosen"
else
	echo "$chosen" | tr -d '\n' | xclip -selection clipboard
	echo "$chosen" | tr -d '\n' | wl-copy
	notify-send "'$chosen' copied to clipboard." &
fi
