#!/bin/sh

chosen=$(cut -d ';' -f1 ~/.local/share/emoji | $MENU -i -l 30 | sed "s/ .*//")

[ -z "$chosen" ] && exit

xdotool type "$chosen"
if [ -n "$1" ]; then
	xdotool type "$chosen"
else
	echo "$chosen" | tr -d '\n' | xclip -selection clipboard
	echo "$chosen" | tr -d '\n' | wl-copy
	notify-send "'$chosen' copied to clipboard." &
fi
